export const categories = [
    {
        name: 'Sport',
        thumbnail: require('../../assets/thumbnails/categories/sport.png'),
        color: '#F88A38',
        flex: 1.6,
        thumbnailSize: 128,
    },
    {
        name: 'Movies',
        thumbnail: require('../../assets/thumbnails/categories/movies.png'),
        color: '#D1B281',
        flex: 1,
        thumbnailSize: 128,
    },
    {
        name: 'Creativity',
        thumbnail: require('../../assets/thumbnails/categories/creativity.png'),
        color: '#A039BD',
        flex: 0.5,
        thumbnailSize: 84,
    },
    {
        name: 'Food',
        thumbnail: require('../../assets/thumbnails/categories/food.png'),
        color: '#C11C0D',
        flex: 1,
        thumbnailSize: 108,
    },
    {
        name: 'Volunteering',
        thumbnail: require('../../assets/thumbnails/categories/volunteering.png'),
        color: '#E3A717',
        flex: 1,
        thumbnailSize: 116,
    },
    {
        name: 'Animals',
        thumbnail: require('../../assets/thumbnails/categories/animals.png'),
        color: '#BB9F7E',
        flex: 1,
        thumbnailSize: 128,
    },
    {
        name: 'Ecology',
        thumbnail: require('../../assets/thumbnails/categories/ecology.png'),
        color: '#00C108',
        flex: 1.3,
        thumbnailSize: 108,
    },
    {
        name: 'Travelenging',
        thumbnail: require('../../assets/thumbnails/categories/traveling.png'),
        color: '#253682',
        flex: 1,
        thumbnailSize: 108,
    },
    {
        name: 'Science',
        thumbnail: require('../../assets/thumbnails/categories/science.png'), 
        color: '#F86EDE',
        flex: 0.75,
        thumbnailSize: 120,
    },
    {
        name: 'Jokes',
        thumbnail: require('../../assets/thumbnails/categories/jokes.png'),
        color: '#0069B4',
        flex: 1,
        thumbnailSize: 120,
    },
    {
        name: 'Programming',
        thumbnail: require('../../assets/thumbnails/categories/programming.png'),
        color: '#BDBDBD',
        flex: 1,
        thumbnailSize: 108,
    },
    {
        name: 'Fashion',
        thumbnail: require('../../assets/thumbnails/categories/fashion.png'),
        color: '#89BEE8',
        flex: 1,
        thumbnailSize: 108,
    },
    {
        name: 'Diy',
        thumbnail: require('../../assets/thumbnails/categories/diy.png'),
        color: '#A9A3A5',
        flex: 1,
        thumbnailSize: 108,
    },
    {
        name: 'Education',
        thumbnail: require('../../assets/thumbnails/categories/education.png'),
        color: '#DE392D',
        flex: 1,
        thumbnailSize: 108,
    },
    {
        name: 'Finance',
        thumbnail: require('../../assets/thumbnails/categories/finance.png'),
        color: '#C09D44',
        flex: 1,
        thumbnailSize: 108,
    },
    {
        name: 'Shitpost',
        thumbnail: require('../../assets/thumbnails/categories/shitpost.png'),
        color: '#68381E',
        flex: 1,
        thumbnailSize: 108,
    }
]