export const categories = [
    {
        name: 'Art',
        thumbnail: require('../../assets/thumbnails/categories/art.webp'),
        color: '#CB9C6D',
        flex: 1.6,
        thumbnailSize: 128,
        secondaryColor: '#754F2A',
    },
    {
        name: 'Games',
        thumbnail: require('../../assets/thumbnails/categories/games.webp'),
        color: '#9C937B',
        flex: 1,
        thumbnailSize: 128,
        secondaryColor: '#494437',
    },
    {
        name: 'Food',
        thumbnail: require('../../assets/thumbnails/categories/food.webp'),
        color: '#D07A32',
        flex: 0.5,
        thumbnailSize: 84,
        secondaryColor: '#573314',
    },
    {
        name: 'Fun stuff',
        thumbnail: require('../../assets/thumbnails/categories/fun.webp'),
        color: '#E6DBCB',
        flex: 1,
        thumbnailSize: 108,
        secondaryColor: '#B49464',
    },
    {
        name: 'Science',
        thumbnail: require('../../assets/thumbnails/categories/science.webp'),
        color: '#948A7B',
        flex: 1,
        thumbnailSize: 116,
        secondaryColor: '#413C35',
    },
    {
        name: 'Traveling',
        thumbnail: require('../../assets/thumbnails/categories/traveling.webp'),
        color: '#AE5C26',
        flex: 1,
        thumbnailSize: 128,
        secondaryColor: '#321B0B',
    },
    {
        name: 'Animals',
        thumbnail: require('../../assets/thumbnails/categories/animals.webp'),
        color: '#748349',
        flex: 1.3,
        thumbnailSize: 108,
        secondaryColor: '#3A4224',
    },
    {
        name: 'Fashion',
        thumbnail: require('../../assets/thumbnails/categories/fashion.webp'),
        color: '#DBD2C4',
        flex: 1,
        thumbnailSize: 108,
        secondaryColor: '#A08964',
    },
    {
        name: 'Other',
        thumbnail: require('../../assets/thumbnails/categories/other.webp'), 
        color: '#EAB57B',
        flex: 0.75,
        thumbnailSize: 120,
        secondaryColor: '#B0691C',
    },
    {
        name: 'Movies',
        thumbnail: require('../../assets/thumbnails/categories/movies.webp'),
        color: '#8C6851',
        flex: 1,
        thumbnailSize: 120,
        secondaryColor: '#2A1F18',
    },
    {
        name: 'Finance',
        thumbnail: require('../../assets/thumbnails/categories/finance.webp'),
        color: '#DFBA84',
        flex: 1,
        thumbnailSize: 108,
        secondaryColor: '#A2712A',
    },
    {
        name: 'Shitpost',
        thumbnail: require('../../assets/thumbnails/categories/shitpost.webp'),
        color: '#777472',
        flex: 1,
        thumbnailSize: 108,
        secondaryColor: '#2A2928',
    }
]